# Generated by Django 3.2.3 on 2021-05-24 09:53

from django.db import migrations, models
import django.db.models.deletion

from work.load.work_dump import load_works


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Детали договора',
                'verbose_name_plural': 'Детали договора',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последних изменений')),
                ('name', models.CharField(help_text='Название (описание) карточки', max_length=50, verbose_name='Название (описание) карточки')),
                ('source_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник информации')),
                ('source_content', models.TextField(blank=True, null=True, verbose_name='Текст статьи/сообщения ')),
                ('city_name', models.CharField(max_length=100, null=True, verbose_name='Город (населённый пункт)')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='Название организации')),
                ('rightsViolationAnother', models.CharField(help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('rightsViolationCaseAnother', models.CharField(help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('case_date', models.DateTimeField(verbose_name='Дата нарушения')),
                ('agency_name', models.CharField(max_length=500, null=True, verbose_name='Название органа')),
                ('intruder_another', models.CharField(max_length=500, null=True, verbose_name='Информация о нарушителе прав')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Точные имена, даты, места событий')),
                ('rights_state_another', models.CharField(help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('victim_situation_another', models.CharField(help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('case_text', models.TextField(blank=True, max_length=1800, null=True, verbose_name='Кейсы, связанные с забастовкой')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='EmployeesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Количество сотрудников предприятия',
                'verbose_name_plural': 'Количество сотрудников предприятия',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='GroupOfRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Группа прав',
                'verbose_name_plural': 'Группы прав',
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Характеристика группы',
                'verbose_name_plural': 'Характеристики групп',
            },
        ),
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушитель',
                'verbose_name_plural': 'Нарушители',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Состояние в браке',
                'verbose_name_plural': 'Состояния в браке',
            },
        ),
        migrations.CreateModel(
            name='MembershipOfGroupPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Членство в профсоюзе участников группы',
                'verbose_name_plural': 'Членство в профсоюзе участников группы',
            },
        ),
        migrations.CreateModel(
            name='NatureViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Характер нарушения',
                'verbose_name_plural': 'Характеры нарушения',
            },
        ),
        migrations.CreateModel(
            name='OwnerShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Формы собственности',
            },
        ),
        migrations.CreateModel(
            name='RightsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ситуация с правами',
                'verbose_name_plural': 'Ситуации с правами',
            },
        ),
        migrations.CreateModel(
            name='RightsViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('groupOfRights', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.groupofrights', verbose_name='Группа прав')),
            ],
            options={
                'verbose_name': 'Нарушение прав',
                'verbose_name_plural': 'Нарушения прав',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник информации',
                'verbose_name_plural': 'Источники информации',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Численность профсоюза после произошедшего',
                'verbose_name_plural': 'Численность профсоюза после произошедшего',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название федерации, конфедерации профсоюзов', max_length=500, verbose_name='Объединение ')),
                ('branch_name', models.CharField(help_text='Название отраслевой профсоюзной организации', max_length=500, verbose_name='Название отраслевой профсоюзной организации')),
                ('victim_name', models.CharField(help_text='федерация, отраслевое объединение, первичная организация', max_length=500, verbose_name='Название организации, права которой были нарушены ')),
                ('contacts', models.CharField(help_text='электронная почта, адрес\\телефон', max_length=500, verbose_name='Контактные данные этой организации')),
            ],
            options={
                'verbose_name': 'Профсоюзная организация',
                'verbose_name_plural': 'Профсоюзные организации',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Профсоюз на месте работы после произошедшего',
                'verbose_name_plural': 'Профсоюзы на месте работы после произошедшего ',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Лицо или организация',
                'verbose_name_plural': 'Лица или организации',
            },
        ),
        migrations.CreateModel(
            name='VictimSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ситуация с потерпевшим(и)',
                'verbose_name_plural': 'Ситуации с потерпевшим(и)',
            },
        ),
        migrations.CreateModel(
            name='RightsViolationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('rightsViolation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.rightsviolation', verbose_name='Нарушение прав')),
            ],
            options={
                'verbose_name': 'Тип нарушения права',
                'verbose_name_plural': 'Типы нарушения прав',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='IndividualInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='анонимно', help_text='ФИО', max_length=50, verbose_name='ФИО')),
                ('member_of_tradeunion', models.BooleanField(default=True, verbose_name='Член профсоюза')),
                ('age', models.CharField(help_text='Возраст пострадавшего', max_length=50, verbose_name='Возраст пострадавшего')),
                ('position', models.CharField(help_text='Должность в организации', max_length=50, verbose_name='Должность в организации')),
                ('experience', models.CharField(help_text='Стаж работы в организации', max_length=50, verbose_name='Стаж работы в организации')),
                ('is_official', models.BooleanField(default=True, verbose_name='Было ли официальное трудоустройство? ')),
                ('has_agreement', models.BooleanField(default=False, verbose_name='Был ли подписан трудовой договор?')),
                ('agreementDetail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.agreementdetail', verbose_name='Детали договора')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.case', verbose_name='Карточка')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.education', verbose_name='Образование')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.gender', verbose_name='Пол пострадавшего')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.maritalstatus', verbose_name='Состояние в браке')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='GroupOfPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(help_text='Количество лиц в группе ', max_length=50, verbose_name='Количество лиц в группе ')),
                ('type_another', models.CharField(max_length=50, null=True, verbose_name='Другое')),
                ('membership_another', models.CharField(max_length=50, null=True, verbose_name='Другое')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.membershipofgrouppersons', verbose_name='Членство в профсоюзе ')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.grouptype', verbose_name='Характеристика группы')),
            ],
            options={
                'verbose_name': 'Группа лиц',
                'verbose_name_plural': 'Группы лиц',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=100, verbose_name='Название')),
                ('address', models.CharField(help_text='Адрес', max_length=100, verbose_name='Адрес')),
                ('product_type', models.CharField(help_text='Вид производимой продукции / Предоставляемые услуги ', max_length=100, verbose_name='Вид производимой продукции / Предоставляемые услуги ')),
                ('experience', models.CharField(help_text='Время на рынке ', max_length=100, verbose_name='Время на рынке')),
                ('branch', models.CharField(help_text='Отрасль деятельности', max_length=100, verbose_name='Отрасль деятельности')),
                ('additional', models.CharField(help_text='Иная важная информация ', max_length=500, verbose_name='Иная важная информация ')),
                ('country_from', models.CharField(help_text='Страна происхождения кампании', max_length=100, verbose_name='Страна происхождения компании')),
                ('is_tnk_member', models.BooleanField(default=False, verbose_name='Является ли эта компания частью ТНК?')),
                ('tnk_name', models.CharField(help_text='Название ТНК, в которую входит эта компания', max_length=100, verbose_name='Название ТНК, в которую входит эта компания')),
                ('emp_count', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.employeescount', verbose_name='Численность работников')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.ownershiptype', verbose_name='Форма собственности компании')),
            ],
            options={
                'verbose_name': 'Работодатель (компания)',
                'verbose_name_plural': 'Работодатели (компании)',
            },
        ),
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.case')),
            ],
            options={
                'verbose_name': 'Фото/видео/документы ',
                'verbose_name_plural': 'Фото/видео/документы ',
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.case')),
            ],
            options={
                'verbose_name': 'Кейсы, связанные с забастовкой',
                'verbose_name_plural': 'Кейсы, связанные с забастовкой',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.company', verbose_name='Работодатель(компания)'),
        ),
        migrations.AddField(
            model_name='case',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.groupofpersons', verbose_name='Группа лиц'),
        ),
        migrations.AddField(
            model_name='case',
            name='intruder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='work.intruder', verbose_name='Нарушитель'),
        ),
        migrations.AddField(
            model_name='case',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='case',
            name='rightsViolation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.rightsviolation', verbose_name='Какое право нарушено'),
        ),
        migrations.AddField(
            model_name='case',
            name='rightsViolationCase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.rightsviolationcase', verbose_name='Тип нарушения права'),
        ),
        migrations.AddField(
            model_name='case',
            name='rights_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.rightsstate', verbose_name='Ситуация с правами'),
        ),
        migrations.AddField(
            model_name='case',
            name='source',
            field=models.ManyToManyField(to='work.Source', verbose_name='Источник информации о нарушении'),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.victimsituation', verbose_name='Ситуация с потерпевшим(и)'),
        ),
        migrations.AddField(
            model_name='case',
            name='violation_nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.natureviolation', verbose_name='Характер нарушения'),
        ),
        migrations.RunPython(load_works),
    ]
