# Generated by Django 3.2.3 on 2021-05-31 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import work.models
from work.load.work_dump import load_works


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Детали договора',
                'verbose_name_plural': 'Детали договора',
            },
        ),
        migrations.CreateModel(
            name='AntiTradeUnionDiscrimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последних изменений')),
                ('case_name', models.CharField(help_text='Название (описание) карточки', max_length=50, verbose_name='Название (описание) карточки')),
                ('source_another', models.CharField(blank=True, max_length=50, null=True, verbose_name='Другое')),
                ('source_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник информации')),
                ('source_content', models.TextField(blank=True, null=True, verbose_name='Текст статьи/сообщения ')),
                ('city_name', models.CharField(max_length=100, verbose_name='Город (населённый пункт)')),
                ('case_company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации')),
                ('tradeUnionRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('tradeUnionCrimeAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('meetingsRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('tradeUnionBuildingsRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('createOrganizationRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('createTradeUnionRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('electionsRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('tradeUnionActivityRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('createStrikeRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('antiTradeUnionDiscriminationAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('conversationRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('сonvention135Another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('consultationRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('discriminationInVariousAreasAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата завершения')),
                ('intruderAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('government_agency_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название государственного органа, полное с указанием территориальной принадлежности ')),
                ('local_agency_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название органа местного самоуправления, полное с указанием территориальной принадлежности ')),
                ('police_agency_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название правоохранительного органа, полное с указанием территориальной принадлежности ')),
                ('exact_data', models.CharField(blank=True, max_length=200, null=True, verbose_name='Укажите точные имена, даты, места событий')),
                ('case_description', models.CharField(max_length=1800, null=True, verbose_name='Укажите ПОСЛЕДОВАТЕЛЬНО, что произошло. Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений)')),
                ('rights_state_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('victim_situation_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('tradeUnionSituation_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('case_text', models.TextField(blank=True, max_length=1800, null=True, verbose_name='Кейсы, связанные с забастовкой')),
                ('antiTradeUnionDiscrimination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.antitradeuniondiscrimination', verbose_name='Антипрофсоюзная дискриминация')),
            ],
        ),
        migrations.CreateModel(
            name='ChildLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='CreateOrganizationRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Создание организации без предварительного разрешения',
                'verbose_name_plural': 'Создания организации без предварительного разрешения',
            },
        ),
        migrations.CreateModel(
            name='CreateStrikeRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушение права на забастовку',
                'verbose_name_plural': 'Нарушения прав на забастовку',
            },
        ),
        migrations.CreateModel(
            name='CreateTradeUnionRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Создание профсоюзов без предварительного разрешения',
                'verbose_name_plural': 'Создания профсоюзов без предварительного разрешения',
            },
        ),
        migrations.CreateModel(
            name='DiscriminationInVariousAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='DiscriminatiOnVariousGrounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='ElectionsRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушение права свободно выбирать своих представителей',
                'verbose_name_plural': 'Нарушения права свободно выбирать своих представителей',
            },
        ),
        migrations.CreateModel(
            name='EmployeesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Количество сотрудников предприятия',
                'verbose_name_plural': 'Количество сотрудников предприятия',
            },
        ),
        migrations.CreateModel(
            name='FailureSystemicMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='GovernmentCoercion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Группа прав',
                'verbose_name_plural': 'Группы прав',
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Характеристика группы',
                'verbose_name_plural': 'Характеристики групп',
            },
        ),
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушитель',
                'verbose_name_plural': 'Нарушители',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Состояние в браке',
                'verbose_name_plural': 'Состояния в браке',
            },
        ),
        migrations.CreateModel(
            name='MeetingsRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушение права на проведение собраний и демонстраций',
                'verbose_name_plural': 'Нарушения права на проведение собраний и демонстраций',
            },
        ),
        migrations.CreateModel(
            name='MembershipOfGroupPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Членство в профсоюзе участников группы',
                'verbose_name_plural': 'Членство в профсоюзе участников группы',
            },
        ),
        migrations.CreateModel(
            name='NatureViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Характер нарушения',
                'verbose_name_plural': 'Характеры нарушения',
            },
        ),
        migrations.CreateModel(
            name='OwnerShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Формы собственности',
            },
        ),
        migrations.CreateModel(
            name='PrincipleOfNonDiscrimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='ProhibitionOfForcedLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='PublicPolicyDiscrimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='RightsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ситуация с правами',
                'verbose_name_plural': 'Ситуации с правами',
            },
        ),
        migrations.CreateModel(
            name='RightsViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('groupOfRights', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.groupofrights', verbose_name='Группа прав')),
            ],
            options={
                'verbose_name': 'Нарушение прав',
                'verbose_name_plural': 'Нарушения прав',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник информации',
                'verbose_name_plural': 'Источники информации',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionActivityRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушение права профсоюза организовывать деятельность своего аппарата',
                'verbose_name_plural': 'Нарушения права профсоюза организовывать деятельность своего аппарата',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionBuildingsRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Защита профсоюзных помещений и имущества профсоюзов',
                'verbose_name_plural': 'Защиты профсоюзных помещений и имущества профсоюзов',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Численность профсоюза после произошедшего',
                'verbose_name_plural': 'Численность профсоюза после произошедшего',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Обвинения в преступном поведении в связи с профсоюзной деятельностью',
                'verbose_name_plural': 'Обвинения в преступном поведении в связи с профсоюзной деятельностью',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeunion_name', models.CharField(max_length=500, verbose_name='Укажите объединение (название федерации, конфедерации профсоюзов) ')),
                ('branch_name', models.CharField(max_length=500, verbose_name='Название отраслевой профсоюзной организации')),
                ('victim_name', models.CharField(max_length=500, verbose_name='Название организации, права которой были нарушены (федерация, отраслевое объединение, первичная организация) ')),
                ('contacts', models.CharField(help_text='электронная почта, адрес\\телефон', max_length=500, verbose_name='Контактные данные этой организации (электронная почта, адрес\\телефон) ')),
            ],
            options={
                'verbose_name': 'Профсоюзная организация',
                'verbose_name_plural': 'Профсоюзные организации',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушение в сфере профсоюзных прав и гражданских свобод',
                'verbose_name_plural': 'Нарушения в сфере профсоюзных прав и гражданских свобод',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Профсоюз на месте работы после произошедшего',
                'verbose_name_plural': 'Профсоюзы на месте работы после произошедшего ',
            },
        ),
        migrations.CreateModel(
            name='UseOfForcedLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Лицо или организация',
                'verbose_name_plural': 'Лица или организации',
            },
        ),
        migrations.CreateModel(
            name='VictimSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ситуация с потерпевшим(и)',
                'verbose_name_plural': 'Ситуации с потерпевшим(и)',
            },
        ),
        migrations.CreateModel(
            name='ViolationsUsingCompulsoryLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Сonvention135',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Сonvention138',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Сonvention182',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Сonvention87',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Сonvention98',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='СonversationRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='RightsViolationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('rightsViolation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.rightsviolation', verbose_name='Нарушение прав')),
            ],
            options={
                'verbose_name': 'Тип нарушения права',
                'verbose_name_plural': 'Типы нарушения прав',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='IndividualInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonim', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Анонимно')),
                ('name', models.CharField(blank=True, help_text='ФИО', max_length=100, null=True, verbose_name='ФИО')),
                ('member_of_tradeunion', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Член профсоюза')),
                ('age', models.CharField(help_text='Возраст пострадавшего', max_length=50, verbose_name='Возраст пострадавшего')),
                ('position', models.CharField(help_text='Должность в организации', max_length=50, verbose_name='Должность в организации')),
                ('experience', models.CharField(help_text='Стаж работы в организации', max_length=50, verbose_name='Стаж работы в организации')),
                ('is_official', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Было ли официальное трудоустройство?')),
                ('has_agreement', models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, null=True, verbose_name='Был ли подписан трудовой договор?')),
                ('agreementDetail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.agreementdetail', verbose_name='Детали договора')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.case', verbose_name='Карточка')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.education', verbose_name='Образование')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.gender', verbose_name='Пол пострадавшего')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.maritalstatus', verbose_name='Состояние в браке')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='GroupOfPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(help_text='Количество лиц в группе ', max_length=50, verbose_name='Количество лиц в группе ')),
                ('type_another', models.CharField(blank=True, max_length=50, null=True, verbose_name='Другое')),
                ('membership_another', models.CharField(blank=True, max_length=50, null=True, verbose_name='Другое')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.membershipofgrouppersons', verbose_name='Членство в профсоюзе ')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.grouptype', verbose_name='Характеристика группы')),
            ],
            options={
                'verbose_name': 'Группа лиц',
                'verbose_name_plural': 'Группы лиц',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Название', max_length=100, verbose_name='Название организации (с указанием организационно-правовой формы)')),
                ('address', models.CharField(help_text='Адрес', max_length=100, verbose_name='Адрес / Телефон')),
                ('product_type', models.CharField(help_text='Вид производимой продукции / Предоставляемые услуги ', max_length=100, verbose_name='Вид производимой продукции / Предоставляемые услуги ')),
                ('country_from', models.CharField(help_text='Страна происхождения кампании', max_length=100, verbose_name='Страна происхождения компании')),
                ('is_tnk_member', models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, null=True, verbose_name='Является ли эта кампания частью ТНК (Транснациональная компания)')),
                ('tnk_name', models.CharField(help_text='Название ТНК, в которую входит эта компания', max_length=100, verbose_name='Название ТНК, в которую входит эта компания')),
                ('company_experience', models.CharField(help_text='Время на рынке ', max_length=100, verbose_name='Время на рынке')),
                ('branch', models.CharField(help_text='Отрасль деятельности', max_length=100, verbose_name='Отрасль деятельности')),
                ('additional', models.CharField(help_text='Иная важная информация ', max_length=500, verbose_name='Иная важная информация ')),
                ('emp_count', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.employeescount', verbose_name='Численность работников')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.ownershiptype', verbose_name='Форма собственности компании')),
            ],
            options={
                'verbose_name': 'Работодатель (компания)',
                'verbose_name_plural': 'Работодатели (компании)',
            },
        ),
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=work.models.photos_location, verbose_name='Фото/видео/документы')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.case')),
            ],
            options={
                'verbose_name': 'Фото/видео/документы ',
                'verbose_name_plural': 'Фото/видео/документы ',
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=work.models.files_location, verbose_name='Кейсы, связанные с забастовкой')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.case')),
            ],
            options={
                'verbose_name': 'Кейсы, связанные с забастовкой',
                'verbose_name_plural': 'Кейсы, связанные с забастовкой',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='childLabor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.childlabor', verbose_name='Использование детского труда'),
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.company', verbose_name='Работодатель(компания)'),
        ),
        migrations.AddField(
            model_name='case',
            name='consultationRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.consultationright', verbose_name='Проведение консультаций'),
        ),
        migrations.AddField(
            model_name='case',
            name='convention182',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.сonvention182', verbose_name='О запрещении и немедленных мерах по искоренению наихудших форм детского труда'),
        ),
        migrations.AddField(
            model_name='case',
            name='conversationRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.сonversationright', verbose_name='Нарушения права на проведение коллективных переговоров'),
        ),
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='case',
            name='createOrganizationRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.createorganizationright', verbose_name='Создание организации без предварительного разрешения'),
        ),
        migrations.AddField(
            model_name='case',
            name='createStrikeRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.createstrikeright', verbose_name='Нарушение права на забастовку'),
        ),
        migrations.AddField(
            model_name='case',
            name='createTradeUnionRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.createtradeunionright', verbose_name='Создание профсоюзов и вступление в профсоюзы'),
        ),
        migrations.AddField(
            model_name='case',
            name='discriminatiOnVariousGrounds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.discriminationvariousgrounds', verbose_name='Дискриминация по различным основаниям'),
        ),
        migrations.AddField(
            model_name='case',
            name='discriminationInVariousAreas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.discriminationinvariousareas', verbose_name='Дискриминация в различных сферах трудовых отношений'),
        ),
        migrations.AddField(
            model_name='case',
            name='electionsRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.electionsright', verbose_name='Нарушение права свободно выбирать своих представителей'),
        ),
        migrations.AddField(
            model_name='case',
            name='failureSystemicMeasures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.failuresystemicmeasures', verbose_name='Нарушения, связанные с непринятием государством системных мер'),
        ),
        migrations.AddField(
            model_name='case',
            name='governmentCoercion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.governmentcoercion', verbose_name='Косвенное принуждение государством к труду '),
        ),
        migrations.AddField(
            model_name='case',
            name='groupOfPersons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.groupofpersons', verbose_name='Группа лиц (работников)'),
        ),
        migrations.AddField(
            model_name='case',
            name='groupOfRights',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.groupofrights', verbose_name='Группа прав'),
        ),
        migrations.AddField(
            model_name='case',
            name='intruder',
            field=models.ManyToManyField(to='work.Intruder', verbose_name='Кем было совершено нарушение'),
        ),
        migrations.AddField(
            model_name='case',
            name='meetingsRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.meetingsright', verbose_name='Нарушения права на проведение собраний и демонстраций'),
        ),
        migrations.AddField(
            model_name='case',
            name='principleOfNonDiscrimination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.principleofnondiscrimination', verbose_name='Принцип запрещения дискриминации'),
        ),
        migrations.AddField(
            model_name='case',
            name='prohibitionOfForcedLabor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.prohibitionofforcedlabor', verbose_name='Запрет принудительного труда'),
        ),
        migrations.AddField(
            model_name='case',
            name='publicPolicyDiscrimination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.publicpolicydiscrimination', verbose_name='Нарушения в области проведения государственной политики по искоренению дискриминации и поощрению равенства прав и возможностей\t'),
        ),
        migrations.AddField(
            model_name='case',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='case',
            name='rights_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.rightsstate', verbose_name='Ситуация с правами'),
        ),
        migrations.AddField(
            model_name='case',
            name='source',
            field=models.ManyToManyField(to='work.Source', verbose_name='Источник информации о нарушении'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionActivityRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunionactivityright', verbose_name='Нарушения права профсоюза организовывать деятельность своего аппарата'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionBuildingsRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunionbuildingsright', verbose_name='Защита профсоюзных помещений и имущества профсоюзов'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionCount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunioncount', verbose_name='Численность профсоюза после произошедшего'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionCrime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunioncrime', verbose_name='Обвинения в преступном поведении в связи с профсоюзной деятельностью'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunioninfo', verbose_name='Профсоюзная организация'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionRight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunionright', verbose_name='Нарушение в сфере профсоюзных прав и гражданских свобод'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionSituation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunionsituation', verbose_name='Профсоюз на месте работы после произошедшего'),
        ),
        migrations.AddField(
            model_name='case',
            name='useOfForcedLabor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.useofforcedlabor', verbose_name='Использование принудительного труда'),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='strike_users', to=settings.AUTH_USER_MODEL, verbose_name='Монитор'),
        ),
        migrations.AddField(
            model_name='case',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.victim', verbose_name='В отношении кого совершено нарушение:'),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.victimsituation', verbose_name='Ситуация с потерпевшим(и)'),
        ),
        migrations.AddField(
            model_name='case',
            name='violation_nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.natureviolation', verbose_name='Характер нарушения'),
        ),
        migrations.AddField(
            model_name='case',
            name='violationsUsingCompulsoryLabor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.violationsusingcompulsorylabor', verbose_name='Нарушения при использовании принудительного (обязательного) труда в допустимых случаях'),
        ),
        migrations.AddField(
            model_name='case',
            name='сonvention135',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.сonvention135', verbose_name='Нарушения положений Конвенции МОТ №135'),
        ),
        migrations.AddField(
            model_name='case',
            name='сonvention138',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.сonvention138', verbose_name='О минимальном возрасте для приема на работу'),
        ),
        migrations.AddField(
            model_name='case',
            name='сonvention87',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.сonvention87', verbose_name='Нарушения положений Конвенции МОТ №87'),
        ),
        migrations.AddField(
            model_name='case',
            name='сonvention98',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.сonvention98', verbose_name='Нарушения положений Конвенции МОТ №98'),
        ),
        migrations.RunPython(load_works)
    ]
