# Generated by Django 3.2.3 on 2021-06-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_description',
            field=models.TextField(blank=True, max_length=1800, null=True, verbose_name='Укажите ПОСЛЕДОВАТЕЛЬНО, что произошло. Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='rights_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.rightsstate', verbose_name='Ситуация с правами'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeUnionCount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunioncount', verbose_name='Численность профсоюза после произошедшего'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeUnionSituation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunionsituation', verbose_name='Профсоюз на месте работы после произошедшего'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeunion_actions',
            field=models.TextField(blank=True, max_length=1800, null=True, verbose_name='Опишите, какие действия предприняты профсоюзом/правозащитной организацией. Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='victim_situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.victimsituation', verbose_name='Ситуация с потерпевшим(и)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='violation_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.natureviolation', verbose_name='Характер нарушения'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='age',
            field=models.CharField(max_length=50, verbose_name='Возраст пострадавшего'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='experience',
            field=models.CharField(max_length=50, verbose_name='Стаж работы в организации'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Должность в организации'),
        ),
        migrations.AlterField(
            model_name='tradeunioninfo',
            name='branch_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название отраслевой профсоюзной организации'),
        ),
        migrations.AlterField(
            model_name='tradeunioninfo',
            name='tradeunion_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Укажите объединение (название федерации, конфедерации профсоюзов) '),
        ),
    ]
