# Generated by Django 3.2.3 on 2021-08-26 13:22

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casefile',
            options={'verbose_name': 'Кейсы, связанные с данной ситуацией', 'verbose_name_plural': 'Кейсы, связанные с данной ситуацией'},
        ),
        migrations.AlterField(
            model_name='casefile',
            name='file',
            field=models.FileField(null=True, upload_to=work.models.files_location, verbose_name='Кейсы, связанные с данной ситуацией'),
        ),
        migrations.AlterField(
            model_name='casephoto',
            name='photo',
            field=models.FileField(null=True, upload_to='document/%Y/%m/%d/', verbose_name='Фото/видео/документы'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='is_anonim',
            field=models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Ананимно'),
        ),
    ]
