# Generated by Django 3.2.3 on 2021-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210826_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='additional',
            field=models.CharField(max_length=2000, verbose_name='Иная важная информация (Другие компании, связанные с ней, головная компания, подрядчики, поставщики и пр.)'),
        ),
    ]
