# Generated by Django 3.2.3 on 2021-06-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210602_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
