# Generated by Django 3.2.3 on 2021-11-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_individualinfo_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.gender', verbose_name='Пол пострадавшего'),
        ),
    ]
