# Generated by Django 3.2.3 on 2021-07-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210630_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='governmentCoercion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.governmentcoercion', verbose_name='Косвенное принуждение государством к труду'),
        ),
        migrations.AlterField(
            model_name='case',
            name='publicPolicyDiscrimination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.publicpolicydiscrimination', verbose_name='Нарушения в области проведения государственной политики по искоренению дискриминации и поощрению равенства прав и возможностей'),
        ),
    ]
