# Generated by Django 3.2.3 on 2021-07-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210712_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeUnionActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='trade_union_activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.tradeunionactivities', verbose_name='Отрасль деятельности профсоюза'),
        ),
    ]
