# Generated by Django 3.2.3 on 2021-09-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_company_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.case'),
        ),
    ]
