# Generated by Django 3.2.3 on 2021-11-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_individualinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стаж работы в организации'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.maritalstatus', verbose_name='Состояние в браке'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность в организации'),
        ),
    ]
