# Generated by Django 3.2.3 on 2021-07-30 12:58

from django.db import migrations, models

from work.load.work_dump import load_works


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20210730_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='trade_union_activities_another',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отрасль деятельности профсоюза(Другое)'),
        ),
    ]
    migrations.RunPython(load_works)
