# Generated by Django 3.2.3 on 2021-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20211118_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_from',
            field=models.CharField(blank=True, help_text='Страна происхождения кампании', max_length=100, null=True, verbose_name='Страна происхождения компании'),
        ),
    ]
