# Generated by Django 3.2.3 on 2021-09-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_case_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='interval',
            new_name='date_type',
        ),
    ]
