# Generated by Django 3.2.3 on 2021-09-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_interval_case_date_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='agreementDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.agreementdetail', verbose_name='Детали договора'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='is_official',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, null=True, verbose_name='Было ли официальное трудоустройство?'),
        ),
    ]
