# Generated by Django 3.2.3 on 2021-06-23 09:35

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210621_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='file',
            field=models.FileField(null=True, upload_to=work.models.files_location, verbose_name='Кейсы, связанные с забастовкой'),
        ),
        migrations.AlterField(
            model_name='casephoto',
            name='photo',
            field=models.FileField(null=True, upload_to=work.models.photos_location, verbose_name='Фото/видео/документы'),
        ),
    ]
