# Generated by Django 3.2.3 on 2021-10-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20210909_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='is_anonim',
            field=models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Анонимно'),
        ),
    ]
