# Generated by Django 3.2.3 on 2021-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20210623_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_result',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Чем завершилась ситуация (если завершилась) или состояние в текущий момент'),
        ),
        migrations.AlterField(
            model_name='case',
            name='exact_data',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Укажите точные имена, даты, места событий'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeunion_actions',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Опишите, какие действия предприняты профсоюзом/правозащитной организацией. Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений)'),
        ),
    ]
