# Generated by Django 3.2.3 on 2021-12-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_case_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
