# Generated by Django 3.2.3 on 2021-12-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_case_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата последних изменений'),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
