# Generated by Django 3.2.3 on 2022-05-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20211228_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='work.education', verbose_name='Образование'),
            preserve_default=False,
        ),
    ]
