# Generated by Django 3.2.3 on 2022-05-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_alter_individualinfo_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.education', verbose_name='Образование'),
        ),
    ]
