# Generated by Django 3.2.3 on 2021-07-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
    ]
