# Generated by Django 3.2.3 on 2021-08-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0002_auto_20210826_1922'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.role', verbose_name='Позиция'),
        ),
    ]
