# Generated by Django 3.2.3 on 2021-10-28 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210826_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
