# Generated by Django 3.2.3 on 2021-07-22 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0005_auto_20210630_1644'),
        ('main', '0003_alter_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.country', verbose_name='Страна'),
        ),
    ]
