# Generated by Django 3.2.3 on 2021-10-28 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_position_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.role', verbose_name='Позиция'),
        ),
    ]
