# Generated by Django 3.2.3 on 2021-07-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_position_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.role', verbose_name='Позиция'),
        ),
    ]
