# Generated by Django 3.2.3 on 2021-05-31 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import migrant.models
from migrant.load.migrant_dump import load_migrants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementDetailNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Значение', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Уточнение, если договора нет',
                'verbose_name_plural': 'Уточнения, если договора нет',
            },
        ),
        migrations.CreateModel(
            name='AgreementDetailYes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Значение', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Уточнение, если договор есть',
                'verbose_name_plural': 'Уточнения, если договор есть',
            },
        ),
        migrations.CreateModel(
            name='BanOnEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Запрет на въезд',
                'verbose_name_plural': 'Запреты на въезд',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последних изменений')),
                ('case_name', models.CharField(help_text='Название (описание) карточки', max_length=30, verbose_name='Название (описание) карточки')),
                ('banOnEntryAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('source_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник информации')),
                ('source_content', models.TextField(blank=True, null=True, verbose_name='Текст статьи/сообщения ')),
                ('violatedRightAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('case_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала нарушения')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца нарушения')),
                ('government_agency_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название государственного органа')),
                ('local_agency_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название органа местного самоуправления')),
                ('police_agency_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название правоохранительного органа')),
                ('control_agency_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название контролирующего органа')),
                ('case_additional', models.TextField(max_length=200, verbose_name='Укажите точные имена, даты, места событий')),
                ('story', models.TextField(max_length=1800, verbose_name='Укажите ПОСЛЕДОВАТЕЛЬНО, что произошло. Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений)')),
                ('actions', models.TextField(max_length=200, verbose_name='Опишите, какие действия предприняты профсоюзом/правозащитной организацией. Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений) ')),
                ('final', models.TextField(max_length=1800, verbose_name='Чем завершилась ситуация (если завершилась) или состояние в текущий момент')),
                ('rights_state_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('victim_situation_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('tradeUnionSituation_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('case_additional_info', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Информация')),
                ('frequent_problems', models.TextField(max_length=1800, verbose_name='С какими на ваш взгляд проблемами чаще всего сталкиваются мигранты и почему?')),
                ('decision', models.TextField(max_length=1800, verbose_name='Какие по вашему мнению есть пути решения этих проблем?')),
                ('advice', models.TextField(max_length=1800, verbose_name='Какая помощь на ваш взгляд необходима мигрантам?')),
                ('has_violation_in_covid', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Были ли нарушены Ваши трудовые права во время пандемии?')),
                ('violationType_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('changesInSalary_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('banOnEntry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.banonentry', verbose_name='Запрет на въезд')),
            ],
        ),
        migrations.CreateModel(
            name='ChangesInSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Изменение в зарплате',
                'verbose_name_plural': 'Изменения в зарплате',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='CountryFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='EmployeesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Количество сотрудников предприятия',
                'verbose_name_plural': 'Количество сотрудников предприятия',
            },
        ),
        migrations.CreateModel(
            name='EntrepreneurEmployeesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Количество сотрудников',
                'verbose_name_plural': 'Количество сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Характеристика группы', max_length=150, verbose_name='Характеристика группы')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Характеристика группы',
                'verbose_name_plural': 'Характеристики групп',
            },
        ),
        migrations.CreateModel(
            name='HireWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Способ нанятия на работу',
                'verbose_name_plural': 'Способы нанятий на работу',
            },
        ),
        migrations.CreateModel(
            name='IndividualCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='InfoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник информации',
                'verbose_name_plural': 'Источники информации',
            },
        ),
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушитель',
                'verbose_name_plural': 'Нарушители',
            },
        ),
        migrations.CreateModel(
            name='MembershipOfGroupPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Членство в профсоюзе участников группы',
                'verbose_name_plural': 'Членство в профсоюзе участников группы',
            },
        ),
        migrations.CreateModel(
            name='NatureViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Характер нарушения',
                'verbose_name_plural': 'Характеры нарушения',
            },
        ),
        migrations.CreateModel(
            name='OwnerShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Формы собственности',
            },
        ),
        migrations.CreateModel(
            name='PayWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Способ выдачи',
                'verbose_name_plural': 'Способы выдачи',
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название права', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Нарушенное право',
                'verbose_name_plural': 'Нарушенные права',
            },
        ),
        migrations.CreateModel(
            name='RightsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ситуация с правами',
                'verbose_name_plural': 'Ситуации с правами',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Численность профсоюза после произошедшего',
                'verbose_name_plural': 'Численность профсоюза после произошедшего',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Значение', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Членство в профсоюзе',
                'verbose_name_plural': 'Членства в профсоюзе ',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Профсоюз на месте работы после произошедшего',
                'verbose_name_plural': 'Профсоюзы на месте работы после произошедшего ',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип жертвы нарушения',
                'verbose_name_plural': 'Типы жертв нарушений',
            },
        ),
        migrations.CreateModel(
            name='VictimSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ситуация с потерпевшим(и)',
                'verbose_name_plural': 'Ситуации с потерпевшим(и)',
            },
        ),
        migrations.CreateModel(
            name='VictimStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус пострадавшего/ей',
                'verbose_name_plural': 'Статусы пострадавших',
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип нарушений трудовых прав',
                'verbose_name_plural': 'Типы нарушений трудовых прав',
            },
        ),
        migrations.CreateModel(
            name='WayOfArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Способ прибытия', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Способ прибытия',
                'verbose_name_plural': 'Способы прибытия',
            },
        ),
        migrations.CreateModel(
            name='WayOfFindingWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Способ прибытия', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Способ найти работу',
                'verbose_name_plural': 'Способы найти работу',
            },
        ),
        migrations.CreateModel(
            name='WayOfGettingSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Способ', max_length=150, verbose_name='Способ')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Способ получения зарплаты',
                'verbose_name_plural': 'Способы получения зарплаты',
            },
        ),
        migrations.CreateModel(
            name='WorkBookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Значение', max_length=150, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Есть ли у Вас трудовая книжка?',
                'verbose_name_plural': 'Есть ли у Вас трудовая книжка?',
            },
        ),
        migrations.CreateModel(
            name='WorkingDayDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Длительность', max_length=150, verbose_name='Длительность')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Длительность рабочего дня',
                'verbose_name_plural': 'Длительности рабочего дня',
            },
        ),
        migrations.CreateModel(
            name='WorkPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Цель работы ',
                'verbose_name_plural': 'Цели работы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.country')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(help_text='Количество лиц в группе', max_length=50, verbose_name='Количество лиц в группе')),
                ('workDescription', models.CharField(max_length=50, verbose_name='Опишите чем занимаются люди в организации, права которых нарушены')),
                ('groupType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.grouptype', verbose_name='Характеристика группы')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.membershipofgrouppersons', verbose_name='Членство в профсоюзе ')),
            ],
            options={
                'verbose_name': 'Группа лиц',
                'verbose_name_plural': 'Группы лиц',
            },
        ),
        migrations.CreateModel(
            name='IndividualInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonim', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Аноним?')),
                ('name', models.CharField(help_text='ФИО', max_length=100, verbose_name='ФИО')),
                ('gender_another', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('individual_age', models.CharField(max_length=50, verbose_name='Возраст пострадавшего')),
                ('contacts', models.CharField(help_text='Контактные данные (телефон/адрес) ', max_length=500, verbose_name='Контактные данные (телефон/адрес) ')),
                ('countryAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('city_name', models.CharField(max_length=100, null=True, verbose_name='Город пребывания пострадавшего')),
                ('countryFromAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('city_name_from', models.CharField(max_length=100, null=True, verbose_name='Город/село')),
                ('wayOfArrivalAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('wayOfFindingWorkAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('hasRegistration', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Есть ли у пострадавшего регистрация в стране пребывания?')),
                ('experience', models.CharField(help_text='Стаж работы в организации', max_length=50, verbose_name='Стаж работы в организации')),
                ('hasAgreement', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Был ли подписан трудовой договор?')),
                ('agreementLang', models.CharField(help_text='На каком языке был подписан договор?', max_length=50, verbose_name='На каком языке был подписан договор?')),
                ('understoodTheContents', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Вы поняли содержание договора?')),
                ('hasOverResponsibilities', models.CharField(choices=[('YES', 'Да, говорили одно, а делаем много разной работы'), ('NO', 'Нет, только то, о чем договаривались')], max_length=50, verbose_name='Есть ли у вас обязанности сверх договора?')),
                ('agreementDetailNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.agreementdetailno', verbose_name='Уточнение, если договора нет')),
                ('agreementDetailYes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.agreementdetailyes', verbose_name='Уточнение, если договор есть')),
                ('countryFrom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.countryfrom', verbose_name='Страна исхода пострадавшего')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.education', verbose_name='Образование')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.gender', verbose_name='Пол пострадавшего')),
                ('individual_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.individualcountry', verbose_name='Страна пребывания пострадавшего')),
                ('tradeUnionMembership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.tradeunionmembership', verbose_name='Членство в профсоюзе на данный момент ')),
                ('wayOfArrival', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.wayofarrival', verbose_name='Как пострадавший приехал в страну пребывания?')),
                ('wayOfFindingWork', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.wayoffindingwork', verbose_name='Как пострадавший нашел работу?')),
                ('wayOfGettingSalary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.wayofgettingsalary', verbose_name='Как Вы получаете заработную плату?')),
                ('workBookStatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.workbookstatus', verbose_name='Есть ли у Вас трудовая книжка? ')),
                ('workingDayDuration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.workingdayduration', verbose_name='Как долго длится ваш рабочий день?')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur_is_anonim', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Аноним?')),
                ('entrepreneur_name', models.CharField(help_text='ФИО', max_length=50, verbose_name='ФИО')),
                ('entrepreneur_gender', models.CharField(choices=[('FEMALE', 'Женский'), ('MALE', 'Мужской')], max_length=50, verbose_name='Пол')),
                ('entrepreneur_age', models.CharField(choices=[('1', '20-35'), ('2', '35-50'), ('3', '50-70')], max_length=50, verbose_name='Возраст')),
                ('entrepreneur_address', models.CharField(help_text='Адрес', max_length=100, verbose_name='Адрес')),
                ('entrepreneur_doAgreement', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Оформляет ли он трудовые договора/соглашения с работниками? ')),
                ('entrepreneur_hireWayAnother', models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое')),
                ('entrepreneur_emp_count', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.entrepreneuremployeescount', verbose_name='Численность работников')),
                ('entrepreneur_hireWay', models.ManyToManyField(to='migrant.HireWay', verbose_name='Как нанимает работников?')),
                ('entrepreneur_payWay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.payway', verbose_name='Как выдает заработную плату?')),
                ('entrepreneur_workPurpose', models.ManyToManyField(to='migrant.WorkPurpose', verbose_name='Для какой цели нанимает работников?')),
            ],
            options={
                'verbose_name': 'Работодатель (частное лицо)',
                'verbose_name_plural': 'Работодатели (частное лицо)',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.country', verbose_name='Страна пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Название', max_length=100, verbose_name='Название')),
                ('address', models.CharField(help_text='Адрес', max_length=100, verbose_name='Адрес')),
                ('product_type', models.CharField(help_text='Вид производимой продукции / Предоставляемые услуги ', max_length=100, verbose_name='Вид производимой продукции / Предоставляемые услуги ')),
                ('country_from', models.CharField(help_text='Страна происхождения кампании', max_length=100, verbose_name='Страна происхождения компании')),
                ('is_tnk_member', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Является ли эта компания частью ТНК?')),
                ('tnk_name', models.CharField(help_text='Название ТНК, в которую входит эта компания', max_length=100, verbose_name='Название ТНК, в которую входит эта компания')),
                ('company_experience', models.CharField(max_length=100, verbose_name='Время работы на рынке (в стране, где произошел случай)')),
                ('branch', models.CharField(help_text='Отрасль деятельности', max_length=100, verbose_name='Отрасль деятельности')),
                ('additional', models.CharField(help_text='Иная важная информация ', max_length=500, verbose_name='Иная важная информация')),
                ('emp_count', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.employeescount', verbose_name='Численность работников')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.ownershiptype', verbose_name='Форма собственности компании')),
            ],
            options={
                'verbose_name': 'Работодатель (компания)',
                'verbose_name_plural': 'Работодатели (компании)',
            },
        ),
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=migrant.models.photos_location, verbose_name='Фото/видео/документы')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.case')),
            ],
            options={
                'verbose_name': 'Фото/видео/документы ',
                'verbose_name_plural': 'Фото/видео/документы ',
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=migrant.models.files_location, verbose_name='Кейсы, связанные с забастовкой')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.case')),
            ],
            options={
                'verbose_name': 'Кейсы, связанные с забастовкой',
                'verbose_name_plural': 'Кейсы, связанные с забастовкой',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='changesInSalary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.changesinsalary', verbose_name='Как изменились Ваши доходы из-за COVID-19?'),
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.company', verbose_name='Работодатель(компания)'),
        ),
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='case',
            name='entrepreneur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.entrepreneur', verbose_name='Работодатель(Частное лицо)'),
        ),
        migrations.AddField(
            model_name='case',
            name='individualInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.individualinfo', verbose_name='физическое лицо'),
        ),
        migrations.AddField(
            model_name='case',
            name='intruder',
            field=models.ManyToManyField(to='migrant.Intruder', verbose_name='Кем было совершено нарушение'),
        ),
        migrations.AddField(
            model_name='case',
            name='personGroupInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.persongroup', verbose_name='Группа лиц'),
        ),
        migrations.AddField(
            model_name='case',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='case',
            name='rights_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.rightsstate', verbose_name='Ситуация с правами'),
        ),
        migrations.AddField(
            model_name='case',
            name='source',
            field=models.ManyToManyField(to='migrant.InfoSource', verbose_name='Источник информации о нарушении'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionCount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.tradeunioncount', verbose_name='Численность профсоюза после произошедшего'),
        ),
        migrations.AddField(
            model_name='case',
            name='tradeUnionSituation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.tradeunionsituation', verbose_name='Профсоюз на месте работы после произошедшего '),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Монитор'),
        ),
        migrations.AddField(
            model_name='case',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.victim', verbose_name='В отношении кого совершено нарушение'),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.victimsituation', verbose_name='Ситуация с потерпевшим(и)'),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.victimstatus', verbose_name='Статус пострадавшего/ей'),
        ),
        migrations.AddField(
            model_name='case',
            name='violated_right',
            field=models.ManyToManyField(to='migrant.Right', verbose_name='Какое право нарушено?'),
        ),
        migrations.AddField(
            model_name='case',
            name='violationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.violationtype', verbose_name='С какими нарушениями трудовых прав вы столкнулись из-за COVID-19?'),
        ),
        migrations.AddField(
            model_name='case',
            name='violation_nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.natureviolation', verbose_name='Характер нарушения'),
        ),

        migrations.RunPython(load_migrants)
    ]
