# Generated by Django 3.2.3 on 2021-06-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='advice',
            field=models.TextField(blank=True, max_length=1800, null=True, verbose_name='Какая помощь на ваш взгляд необходима мигрантам?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='decision',
            field=models.TextField(blank=True, max_length=1800, null=True, verbose_name='Какие по вашему мнению есть пути решения этих проблем?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='frequent_problems',
            field=models.TextField(blank=True, max_length=1800, null=True, verbose_name='С какими на ваш взгляд проблемами чаще всего сталкиваются мигранты и почему?'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='agreementDetailNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.agreementdetailno', verbose_name='Уточнение, если договора нет'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='agreementDetailYes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.agreementdetailyes', verbose_name='Уточнение, если договор есть'),
        ),
    ]
