# Generated by Django 3.2.3 on 2021-05-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='additional',
            new_name='case_additional',
        ),
        migrations.AlterField(
            model_name='case',
            name='banOnEntryAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='changesInSalary_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='rights_state_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeUnionSituation_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='victim_situation_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='violationType_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='company',
            name='additional',
            field=models.CharField(help_text='Иная важная информация ', max_length=500, verbose_name='Иная важная информация'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_hireWayAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='agreementDetailNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.agreementdetailno', verbose_name='Уточнение, если договора нет'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='agreementDetailYes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.agreementdetailyes', verbose_name='Уточнение, если договор есть'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='countryAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='countryFromAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='gender_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='wayOfArrivalAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='wayOfFindingWorkAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, verbose_name='Другое'),
        ),
    ]
