# Generated by Django 3.2.3 on 2021-05-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tradeUnionCount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.tradeunioncount', verbose_name='Численность профсоюза после произошедшего'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeUnionSituation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.tradeunionsituation', verbose_name='Профсоюз на месте работы после произошедшего '),
        ),
    ]
