# Generated by Django 3.2.3 on 2021-06-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0002_alter_casefile_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.case'),
        ),
    ]
