# Generated by Django 3.2.3 on 2021-11-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0002_alter_individualinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='name',
            field=models.CharField(blank=True, help_text='ФИО', max_length=100, null=True, verbose_name='ФИО'),
        ),
    ]
