# Generated by Django 3.2.3 on 2021-05-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0002_auto_20210524_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='control_agency_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название контролирующего органа'),
        ),
        migrations.AlterField(
            model_name='case',
            name='government_agency_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название государственного органа'),
        ),
        migrations.AlterField(
            model_name='case',
            name='individualInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.individualinfo', verbose_name='физическое лицо'),
        ),
        migrations.AlterField(
            model_name='case',
            name='local_agency_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название органа местного самоуправления'),
        ),
        migrations.AlterField(
            model_name='case',
            name='personGroupInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.persongroup', verbose_name='Группа лиц'),
        ),
        migrations.AlterField(
            model_name='case',
            name='police_agency_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название правоохранительного органа'),
        ),
    ]
