# Generated by Django 3.2.3 on 2021-08-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0002_auto_20210826_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='additional',
            field=models.CharField(blank=True, help_text='Иная важная информация ', max_length=1500, null=True, verbose_name='Иная важная информация (Другие компании, связанные с ней, головная компания, подрядчики, поставщики и пр.) '),
        ),
    ]
