# Generated by Django 3.2.3 on 2021-06-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0003_alter_case_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Коментрий')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.case')),
            ],
            options={
                'verbose_name': 'Коментарий к мигранту',
                'verbose_name_plural': 'Коментарии к мигрантам',
            },
        ),
    ]
