# Generated by Django 3.2.3 on 2021-11-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0003_alter_individualinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='agreementLang',
            field=models.CharField(blank=True, help_text='На каком языке был подписан договор?', max_length=50, null=True, verbose_name='На каком языке был подписан договор?'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='understoodTheContents',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, null=True, verbose_name='Вы поняли содержание договора?'),
        ),
    ]
