# Generated by Django 3.2.3 on 2021-05-25 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0003_auto_20210524_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_additional_info',
            field=models.CharField(blank=True, max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='case',
            name='banOnEntryAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(help_text='Название (описание) карточки', max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Название (описание) карточки'),
        ),
        migrations.AlterField(
            model_name='case',
            name='changesInSalary_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='rights_state_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Источник информации'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeUnionSituation_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='victim_situation_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='violatedRightAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='case',
            name='violationType_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Кейсы, связанные с забастовкой'),
        ),
        migrations.AlterField(
            model_name='casephoto',
            name='file',
            field=models.FileField(upload_to='photos', verbose_name='Фото/видео/документы'),
        ),
        migrations.AlterField(
            model_name='company',
            name='additional',
            field=models.CharField(help_text='Иная важная информация ', max_length=500, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Иная важная информация'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(help_text='Адрес', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(help_text='Название', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country_from',
            field=models.CharField(help_text='Страна происхождения кампании', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Страна происхождения компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product_type',
            field=models.CharField(help_text='Вид производимой продукции / Предоставляемые услуги ', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Вид производимой продукции / Предоставляемые услуги '),
        ),
        migrations.AlterField(
            model_name='company',
            name='tnk_name',
            field=models.CharField(help_text='Название ТНК, в которую входит эта компания', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Название ТНК, в которую входит эта компания'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_address',
            field=models.CharField(help_text='Адрес', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_name',
            field=models.CharField(default='анонимно', help_text='ФИО', max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='agreementLang',
            field=models.CharField(help_text='На каком языке был подписан договор?', max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='На каком языке был подписан договор?'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='city_name_from',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Город/село'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='contacts',
            field=models.CharField(help_text='Контактные данные (телефон/адрес) ', max_length=500, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Контактные данные (телефон/адрес) '),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='countryAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='countryFromAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='gender_another',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='name',
            field=models.CharField(default='анонимно', help_text='ФИО', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='wayOfArrivalAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='wayOfFindingWorkAnother',
            field=models.CharField(blank=True, help_text='Введите значение', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Значение должно состоять минимум из 3 символов')], verbose_name='Другое'),
        ),
    ]
