# Generated by Django 3.2.3 on 2022-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0004_auto_20211123_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата последних изменений'),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца нарушения'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала нарушения'),
        ),
    ]
