# Generated by Django 3.2.3 on 2021-06-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0004_auto_20210630_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migrant.case'),
        ),
        migrations.AlterField(
            model_name='casephoto',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото/видео/документы'),
        ),
    ]
