# Generated by Django 3.2.3 on 2022-01-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0005_auto_20211228_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_from',
            field=models.CharField(blank=True, help_text='Страна происхождения кампании', max_length=100, verbose_name='Страна происхождения компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_tnk_member',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Является ли эта компания частью ТНК?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tnk_name',
            field=models.CharField(blank=True, help_text='Название ТНК, в которую входит эта компания', max_length=100, verbose_name='Название ТНК, в которую входит эта компания'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_workPurpose',
            field=models.ManyToManyField(blank=True, to='migrant.WorkPurpose', verbose_name='Для какой цели нанимает работников?'),
        ),
    ]
