# Generated by Django 3.2.3 on 2021-06-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0005_auto_20210621_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casecomment',
            options={'verbose_name': 'Комментарий к мигранту', 'verbose_name_plural': 'Комментарии к мигрантам'},
        ),
        migrations.AlterField(
            model_name='case',
            name='source_content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи/сообщения'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tradeUnionSituation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.tradeunionsituation', verbose_name='Профсоюз на месте работы после произошедшего'),
        ),
        migrations.AlterField(
            model_name='casecomment',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
