# Generated by Django 3.2.3 on 2021-06-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0006_auto_20210623_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Кейс мигрант', 'verbose_name_plural': 'Кейсы мигранты'},
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='hasAgreement',
            field=models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], default=0, max_length=20, verbose_name='Был ли подписан трудовой договор?'),
        ),
    ]
