# Generated by Django 3.2.3 on 2022-01-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0007_alter_entrepreneur_entrepreneur_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_hireWay',
            field=models.ManyToManyField(blank=True, null=True, to='migrant.HireWay', verbose_name='Как нанимает работников?'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_workPurpose',
            field=models.ManyToManyField(blank=True, null=True, to='migrant.WorkPurpose', verbose_name='Для какой цели нанимает работников?'),
        ),
    ]
