# Generated by Django 3.2.3 on 2022-01-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0008_auto_20220127_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_hireWay',
            field=models.ManyToManyField(to='migrant.HireWay', verbose_name='Как нанимает работников?'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_name',
            field=models.CharField(blank=True, help_text='ФИО', max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_workPurpose',
            field=models.ManyToManyField(to='migrant.WorkPurpose', verbose_name='Для какой цели нанимает работников?'),
        ),
    ]
