# Generated by Django 3.2.3 on 2022-01-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0009_auto_20220128_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_hireWay',
            field=models.ManyToManyField(blank=True, null=True, to='migrant.HireWay', verbose_name='Как нанимает работников?'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_payWay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.payway', verbose_name='Как выдает заработную плату?'),
        ),
    ]
