# Generated by Django 3.2.3 on 2021-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0011_alter_individualinfo_hasagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casephoto',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото/видео/документы'),
        ),
    ]
