# Generated by Django 3.2.3 on 2021-06-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0012_alter_casephoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.company', verbose_name='Работодатель(компания)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.entrepreneur', verbose_name='Работодатель(Частное лицо)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='individualInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.individualinfo', verbose_name='физическое лицо'),
        ),
    ]
