# Generated by Django 3.2.3 on 2021-06-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0013_auto_20210624_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='migrant.case'),
        ),
    ]
