# Generated by Django 3.2.3 on 2021-05-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='DemandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.CharField(max_length=255, verbose_name='Требование')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип требования',
                'verbose_name_plural': 'Типы требований',
            },
        ),
        migrations.CreateModel(
            name='NumberChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('type', models.CharField(choices=[('COMPANY', 'Для численности сотрудников компании'), ('STRIKE', 'Для численности участников')], max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Выбор числа',
                'verbose_name_plural': 'Выбор чисел',
            },
        ),
        migrations.CreateModel(
            name='OwnerShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Формы собственности',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название источника', max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='TradeUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('visible', models.BooleanField(default=False, verbose_name='Видимый')),
            ],
            options={
                'verbose_name': 'Есть ли на предприятии профсоюзы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='strike.country')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='DemandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('demand_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strike.demandtype', verbose_name='Тип требования')),
            ],
            options={
                'verbose_name': 'Характер требования',
                'verbose_name_plural': 'Характеры требований',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('source_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник информации (ссылка)')),
                ('source_content', models.TextField(blank=True, null=True, verbose_name='Текст статьи/сообщения ')),
                ('city_name', models.CharField(max_length=100, verbose_name='Название города')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название предприятия (юридического лица)')),
                ('card_sources', models.ManyToManyField(to='strike.Source', verbose_name='Источник')),
                ('company_ownership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strike.ownershiptype', verbose_name='Форма собственности компании')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='strike.country', verbose_name='Страна')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='strike.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
