# Generated by Django 3.2.3 on 2021-08-26 13:22

from django.db import migrations, models
import strike.models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardfile',
            options={'verbose_name': 'Кейсы, связанные с данной ситуацией', 'verbose_name_plural': 'Кейсы, связанные с данной ситуацией'},
        ),
        migrations.AlterField(
            model_name='card',
            name='additional_information',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Любая дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='cardfile',
            name='file',
            field=models.FileField(blank=True, upload_to=strike.models.files_location, verbose_name='Кейсы, связанные с данной ситуацией'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='photo',
            field=models.FileField(blank=True, upload_to='document/%Y/%m/%d/', verbose_name='Фото/видео/документы'),
        ),
    ]
