# Generated by Django 3.2.3 on 2021-05-14 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Количество сотрудников предприятия',
                'verbose_name_plural': 'Количество сотрудников предприятия',
            },
        ),
        migrations.CreateModel(
            name='ParticipantsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Количество участников забастовки',
                'verbose_name_plural': 'Количество участников забастовки',
            },
        ),
        migrations.DeleteModel(
            name='NumberChoices',
        ),
        migrations.AddField(
            model_name='card',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Любая дополнительная информация'),
        ),
        migrations.AddField(
            model_name='card',
            name='address_employer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='card',
            name='address_union',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='card',
            name='age',
            field=models.CharField(choices=[('<18', 'менее 18 лет'), ('19-62', '19-62'), ('> 63', '63 и старше')], default='<18', max_length=10, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания карточки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='card_demand_categories',
            field=models.ManyToManyField(to='strike.DemandCategory', verbose_name='Характер требований'),
        ),
        migrations.AddField(
            model_name='card',
            name='change_number_participants',
            field=models.TextField(default='', help_text='Опишите как менялось количество участников забастовки во время проведения и что на это влияло?', verbose_name='Как менялось количество участников забастовки'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_country_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна происхождения компании'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_is_tnk_member',
            field=models.BooleanField(default=False, verbose_name='Является ли эта кампания частью ТНК (Транснациональная компания)'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_tnk_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название ТНК (Транснациональная компания)'),
        ),
        migrations.AddField(
            model_name='card',
            name='duration',
            field=models.CharField(choices=[('-', 'Кратковременная'), ('---', 'Длящаяся')], default='-', max_length=3, verbose_name='Длительность забастовки/акции'),
        ),
        migrations.AddField(
            model_name='card',
            name='employer',
            field=models.CharField(default='', max_length=200, verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 14, 11, 42, 90897), verbose_name='Дата конца проведения забастовки/акции'),
        ),
        migrations.AddField(
            model_name='card',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='card',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.CharField(choices=[('Б/ПГ', 'Бригада или производственная группа'), ('опр категория', 'Определенная категория работников'), ('Др', 'Другое')], default='Б/ПГ', max_length=200, verbose_name='Группа лиц'),
        ),
        migrations.AddField(
            model_name='card',
            name='has_trade_union',
            field=models.CharField(choices=[('+', 'Да'), ('-', 'Отсутствует'), ('?', 'Неизвестно'), ('ДР', 'Другое')], default='+', max_length=50, verbose_name='Профсоюз'),
        ),
        migrations.AddField(
            model_name='card',
            name='initiators_and_participants',
            field=models.TextField(default='', help_text='Ситуация с инициаторами и участниками забастовки/акции (продолжают ли они работать, применялись ли к ним административные меры со стороны предприятия)', verbose_name='Что с инициаторами и участниками'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='card',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='card',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='card',
            name='meeting_requirements',
            field=models.CharField(choices=[('+', 'удовлетворены'), ('-', 'не удовлетворены'), ('+-', 'удовлетворены частично')], default='+', max_length=2, verbose_name='Удовлетворение требований'),
        ),
        migrations.AddField(
            model_name='card',
            name='phone_number_employer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='card',
            name='phone_number_union',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='card',
            name='profession',
            field=models.CharField(default='', max_length=100, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='card',
            name='reasons_for_strike',
            field=models.TextField(default='', help_text='Опишите причины начала забастовки (например: условия труда на предприятии, продолжительность рабочего времени, безопасность ит.д. время, связанное с работой)', verbose_name='Причины начала забастовки'),
        ),
        migrations.AddField(
            model_name='card',
            name='results_so_far',
            field=models.TextField(default='', verbose_name='C какими итогами закончилась забастовка, если еще не закончилась, то какие итоги на данный момент.'),
        ),
        migrations.AddField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 14, 11, 42, 90897), verbose_name='Дата начало проведения забастовки/акции'),
        ),
        migrations.AddField(
            model_name='card',
            name='state_position',
            field=models.TextField(default='', verbose_name='Позиция государства (Опишите реакцию государственных органов)'),
        ),
        migrations.AddField(
            model_name='card',
            name='story',
            field=models.TextField(default='', help_text='Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений)', verbose_name='Укажите ПОСЛЕДОВАТЕЛЬНО, что произошло'),
        ),
        migrations.AddField(
            model_name='card',
            name='trade_union',
            field=models.CharField(default='', max_length=200, verbose_name='Название профсоюза'),
        ),
        migrations.AddField(
            model_name='card',
            name='union_membership',
            field=models.CharField(choices=[('Все', 'Все состоят в профсоюзе'), ('Не все', 'В профсоюзе состоят не все'), ('Никто', 'Никто не состоит в профсоюзе')], default='Все', max_length=200, verbose_name='Членство в профсоюзе'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_employees_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strike.employeescount', verbose_name='Общая численность работников на предприятии'),
        ),
        migrations.AddField(
            model_name='card',
            name='count_strike_participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strike.participantscount', verbose_name='Количество участников забастовки/акции'),
        ),
    ]
