# Generated by Django 3.2.3 on 2021-06-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcomment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strike.card'),
        ),
        migrations.AlterField(
            model_name='cardfile',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strike.card'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strike.card'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото/видео/документы'),
        ),
    ]
