# Generated by Django 3.2.3 on 2021-06-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца проведения забастовки/акции'),
        ),
    ]
