# Generated by Django 3.2.3 on 2021-11-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0002_alter_individual_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strike.age', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=20, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='is_anonim',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, null=True, verbose_name='Анонимно'),
        ),
    ]
