# Generated by Django 3.2.3 on 2021-09-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0002_auto_20210826_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='additional_information',
            field=models.TextField(blank=True, max_length=3600, null=True, verbose_name='Любая дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='card',
            name='change_number_participants',
            field=models.TextField(blank=True, max_length=3600, verbose_name='Опишите как менялось количество участников забастовки во время проведения и что на это влияло?'),
        ),
        migrations.AlterField(
            model_name='card',
            name='initiators_and_participants',
            field=models.TextField(blank=True, max_length=3600, verbose_name='Ситуация с инициаторами и участниками забастовки/акции (продолжают ли они работать, применялись ли к ним административные меры со стороны предприятия). '),
        ),
        migrations.AlterField(
            model_name='card',
            name='reasons_for_strike',
            field=models.TextField(blank=True, max_length=3600, verbose_name='Опишите причины начала забастовки (например: условия труда на предприятии, продолжительность рабочего времени, безопасность и т.д. время, связанное с работой)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='results_so_far',
            field=models.TextField(blank=True, max_length=3600, verbose_name='Опишите, с какими итогами закончилась забастовка, если еще не закончилась, то какие итоги на данный момент.'),
        ),
        migrations.AlterField(
            model_name='card',
            name='state_position',
            field=models.TextField(blank=True, max_length=3600, verbose_name='Позиция государства (Опишите реакцию государственных органов)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='story',
            field=models.TextField(blank=True, max_length=3600, verbose_name='Укажите ПОСЛЕДОВАТЕЛЬНО, что произошло. Параллельно указывайте, чем подтверждаются эти факты (если есть приложения, укажите сразу номера и названия соответствующих приложений) '),
        ),
    ]
