# Generated by Django 3.2.3 on 2021-07-08 10:41

from django.db import migrations, models
import django.db.models.deletion
import strike.models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0003_auto_20210708_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfile',
            name='file',
            field=models.FileField(blank=True, upload_to=strike.models.files_location, verbose_name='Кейсы, связанные с забастовкой'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото/видео/документы'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='age',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strike.age', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='is_anonim',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Анонимно'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Профессия'),
        ),
    ]
