# Generated by Django 3.2.3 on 2021-12-03 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0003_auto_20211124_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strike.card'),
        ),
    ]
