# Generated by Django 3.2.3 on 2021-06-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0004_auto_20210621_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcomment',
            old_name='case',
            new_name='card',
        ),
    ]
