# Generated by Django 3.2.3 on 2021-12-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0004_alter_individual_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата последних изменений'),
        ),
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца проведения забастовки/акции'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateField(verbose_name='Дата начало проведения забастовки/акции'),
        ),
    ]
