# Generated by Django 3.2.3 on 2021-10-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0004_card_date_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_sources',
            field=models.ManyToManyField(related_name='source', to='strike.Source', verbose_name='Источник'),
        ),
    ]
