# Generated by Django 3.2.3 on 2021-06-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0005_rename_case_cardcomment_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradeunion',
            options={'verbose_name': 'Есть ли на предприятии профсоюз', 'verbose_name_plural': 'Есть ли на предприятии профсоюзы'},
        ),
    ]
