# Generated by Django 3.2.3 on 2021-10-28 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strike', '0005_alter_card_card_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Монитор'),
        ),
    ]
