# Generated by Django 3.2.3 on 2021-05-16 07:47

import datetime
from django.db import migrations, models


def load_sources(apps,schema_editor):
    Source = apps.get_model("strike", "Source")
    source = Source(id = 0, name = 'СМИ/Блогер/Лидер мнения', is_active = True)
    source.save()
    source = Source(id = 1, name = 'Работники/участники протеста', is_active = True)
    source.save()
    source = Source(id = 2, name = 'Профсоюз', is_active = True)
    source.save()
    source = Source(id = 3, name = 'Представитель коллектива', is_active = True)
    source.save()
    source = Source(id = 4, name = 'Государственные органы', is_active = True)
    source.save()
    source = Source(id = 5, name = 'Не правительственные организации /гражданские активисты', is_active = True)
    source.save()

def load_countries(apps, schema_editor):
    Country = apps.get_model("strike", "Country")
    country = Country(id=0, name='Россия', is_active=True)
    country.save()
    country = Country(id=1, name='Кыргызстан', is_active=True)
    country.save()
    country = Country(id=2, name='Казахстан', is_active=True)
    country.save()


def load_regions(apps, schema_editor):
    Region = apps.get_model("strike", "Region")
    Country = apps.get_model("strike", "Country")
    region = Region(id=0, name='г. Москва', is_active=True, country = Country(id = 0))
    region.save()
    # region = Region(id=1, name='Кыргызстан', is_active=True)
    # region.save()
    # region = Region(id=2, name='Казахстан', is_active=True)
    # region.save()

class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0005_auto_20210516_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 13, 47, 17, 833035), verbose_name='Дата конца проведения забастовки/акции'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 13, 47, 17, 833035), verbose_name='Дата начало проведения забастовки/акции'),
        ),
        migrations.RunPython(load_sources)
    ]

