# Generated by Django 3.2.3 on 2021-05-16 11:03

import datetime
from django.db import migrations, models
def load_sources(apps,schema_editor):
    Source = apps.get_model("strike", "Source")
    source = Source(id = 0, name = 'СМИ/Блогер/Лидер мнения', is_active = True)
    source.save()
    source = Source(id = 1, name = 'Работники/участники протеста', is_active = True)
    source.save()
    source = Source(id = 2, name = 'Профсоюз', is_active = True)
    source.save()
    source = Source(id = 3, name = 'Представитель коллектива', is_active = True)
    source.save()
    source = Source(id = 4, name = 'Государственные органы', is_active = True)
    source.save()
    source = Source(id = 5, name = 'Не правительственные организации /гражданские активисты', is_active = True)
    source.save()

def load_countries(apps, schema_editor):
    Country = apps.get_model("strike", "Country")
    country = Country(id=0, name='Россия', is_active=True)
    country.save()
    country = Country(id=1, name='Кыргызстан', is_active=True)
    country.save()
    country = Country(id=2, name='Казахстан', is_active=True)
    country.save()


def load_ownership_types(apps, schema_editor):
    OwnerShipType = apps.get_model("strike", "OwnerShipType")
    type = OwnerShipType(id=0, name='Национальная, государственная', is_active=True)
    type.save()
    type = OwnerShipType(id=1, name='Национальная, частная', is_active=True)
    type.save()
    type = OwnerShipType(id=2, name='Смешанная', is_active=True)
    type.save()
    type = OwnerShipType(id=3, name='Иностранная', is_active=True)
    type.save()

def load_regions(apps, schema_editor):
    Region = apps.get_model("strike", "Region")
    Country = apps.get_model("strike", "Country")
    region = Region(id=0, name='г. Москва', is_active=True, country = Country(id = 0))
    region.save()
    # region = Region(id=1, name='Кыргызстан', is_active=True)
    # region.save()
    # region = Region(id=2, name='Казахстан', is_active=True)
    # region.save()

class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0008_auto_20210516_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='card',
            name='address_employer',
        ),
        migrations.RemoveField(
            model_name='card',
            name='address_union',
        ),
        migrations.RemoveField(
            model_name='card',
            name='age',
        ),
        migrations.RemoveField(
            model_name='card',
            name='change_number_participants',
        ),
        migrations.RemoveField(
            model_name='card',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='card',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='card',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='card',
            name='group',
        ),
        migrations.RemoveField(
            model_name='card',
            name='initiators_and_participants',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='meeting_requirements',
        ),
        migrations.RemoveField(
            model_name='card',
            name='phone_number_employer',
        ),
        migrations.RemoveField(
            model_name='card',
            name='phone_number_union',
        ),
        migrations.RemoveField(
            model_name='card',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='card',
            name='reasons_for_strike',
        ),
        migrations.RemoveField(
            model_name='card',
            name='results_so_far',
        ),
        migrations.RemoveField(
            model_name='card',
            name='state_position',
        ),
        migrations.RemoveField(
            model_name='card',
            name='story',
        ),
        migrations.RemoveField(
            model_name='card',
            name='trade_union',
        ),
        migrations.RemoveField(
            model_name='card',
            name='union_membership',
        ),
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 17, 3, 10, 602120), verbose_name='Дата конца проведения забастовки/акции'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 17, 3, 10, 602120), verbose_name='Дата начало проведения забастовки/акции'),
        ),

        migrations.RunPython(load_sources),
        migrations.RunPython(load_countries),
        migrations.RunPython(load_regions),
        migrations.RunPython(load_ownership_types)
    ]
