# Generated by Django 3.2.3 on 2021-05-16 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0012_auto_20210516_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='added_by',
        ),
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 22, 37, 30, 176227), verbose_name='Дата конца проведения забастовки/акции'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 22, 37, 30, 176227), verbose_name='Дата начало проведения забастовки/акции'),
        ),
    ]
