# Generated by Django 3.2.3 on 2021-05-16 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0013_auto_20210516_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_create_date',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='last_update',
            new_name='date_update',
        ),
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 22, 40, 19, 602657), verbose_name='Дата конца проведения забастовки/акции'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 22, 40, 19, 602657), verbose_name='Дата начало проведения забастовки/акции'),
        ),
    ]
