data = {'additional': '',
 'address': '',
 'amount': '',
 'antiTradeUnionDiscrimination': '',
 'antiTradeUnionDiscriminationAnother': '',
 'branch': '',
 'branch_name': '',
 'case_company_name': 'информация о нарушении, допущенном в отношении человека '
                      'лично',
 'case_description': '',
 'case_name': 'ОБЩАЯ ИНФОРМАЦИЯ  Название (описание) карточки:',
 'case_result': '',
 'case_text': '',
 'childLabor': '',
 'city_name': 'информация о нарушении, допущенном в отношении человека лично',
 'company_experience': '',
 'company_name': '',
 'consultationRight': '',
 'consultationRightAnother': '',
 'contacts': '',
 'convention182': '',
 'conversationRight': '',
 'conversationRightAnother': '',
 'country': '3',
 'country_from': '',
 'createOrganizationRight': '',
 'createOrganizationRightAnother': '',
 'createStrikeRight': '',
 'createStrikeRightAnother': '',
 'createTradeUnionRight': '',
 'createTradeUnionRightAnother': '',
 'csrfmiddlewaretoken': 'CsXwB0ixOnUAvAmcZJlUhbP5mw1XPRONpKHBhlhrSZ6lyFzK2Y84Z0Fz3bCI4k3P',
 'date_type': '0',
 'discriminatiOnVariousGrounds': '',
 'discriminationInVariousAreas': '',
 'discriminationInVariousAreasAnother': '',
 'electionsRight': '',
 'electionsRightAnother': '',
 'emp_count': '',
 'end_date': '',
 'exact_data': '',
 'failureSystemicMeasures': '',
 'file': '',
 'form-0-age': '1',
 'form-0-agreementDetail': '',
 'form-0-education': '1',
 'form-0-experience': '6',
 'form-0-gender': '1',
 'form-0-has_agreement': 'NO',
 'form-0-id': '',
 'form-0-is_anonim': 'YES',
 'form-0-is_official': 'YES',
 'form-0-marital_status': '2',
 'form-0-member_of_tradeunion': 'YES',
 'form-0-name': '',
 'form-0-position': 'reast',
 'form-INITIAL_FORMS': '',
 'form-MAX_NUM_FORMS': '',
 'form-MIN_NUM_FORMS': '',
 'form-TOTAL_FORMS': '',
 'governmentCoercion': '',
 'government_agency_name': '',
 'groupOfRights': '4',
 'intruder': '5',
 'intruderAnother': '',
 'is_tnk_member': '',
 'local_agency_name': '',
 'meetingsRight': '',
 'meetingsRightAnother': '',
 'membership': '',
 'membership_another': '',
 'ownership': '',
 'photo': '',
 'police_agency_name': '',
 'principleOfNonDiscrimination': '',
 'product_type': '',
 'prohibitionOfForcedLabor': '',
 'publicPolicyDiscrimination': '',
 'region': '58',
 'rights_state': '',
 'rights_state_another': '',
 'source': '6',
 'source_another': '',
 'source_content': '',
 'source_url': '',
 'start_date': '2021-12-03',
 'submit': 'Сохранить',
 'tnk_name': '',
 'tradeUnionActivityRight': '',
 'tradeUnionActivityRightAnother': '',
 'tradeUnionBuildingsRight': '',
 'tradeUnionBuildingsRightAnother': '',
 'tradeUnionCount': '',
 'tradeUnionCrime': '',
 'tradeUnionCrimeAnother': '',
 'tradeUnionRight': '',
 'tradeUnionRightAnother': '',
 'tradeUnionSituation': '',
 'tradeUnionSituation_another': '',
 'trade_union_activities': '17',
 'trade_union_activities_another': '',
 'tradeunion_actions': '',
 'tradeunion_name': '',
 'type': '',
 'type_another': '',
 'useOfForcedLabor': '',
 'victim': '2',
 'victim_name': '',
 'victim_situation': '',
 'victim_situation_another': '',
 'violation_nature': '',
 'violationsUsingCompulsoryLabor': '',
 'сonvention135': '2',
 'сonvention135Another': '',
 'сonvention138': '',
 'сonvention87': '',
 'сonvention98': ''}

def form_formset(data):
 a = {}
 for i,y in data.items():
  if i.endswith('id'):
    data.pop(i)
  if i.startswith('form'):
   a.update({
   i:y
  })
 print(a)

form_formset(data)



def total_forms(data):
 if len(data['form-TOTAL_FORMS']) == 0:
  data['form-TOTAL_FORMS'] = '1';
# print(data)